development:
  adapter: postgresql
  database: sphinx_development
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sphinx_test
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: sphinx_production
  username: postgres
  password: postgres
  host: localhost
  pool: 5
  timeout: 5000
